# Generated by Django 4.0.3 on 2022-04-04 14:56

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to=myapp.models.filepath)),
                ('rate', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=500)),
                ('cate', models.CharField(max_length=500)),
                ('year', models.CharField(max_length=100)),
            ],
        ),
    ]
